spring:
  application.name: loader-service
  cloud:
    zookeeper:
      connect-string: localhost:2181

server.port: 21000

mongo:
  uri: mongodb://localhost:27017/aoc_aop?authSource=admin

elasticsearch:
  url: localhost
  port: 9300
  index: aoc_aop