spring:
  application.name: kpi-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

server.port: 21001

elasticsearch:
  url: localhost
  port: 9300
  index: aoc_aop
